

spring:
  config:
    name: dev
  application:
    name: chat
  database:
    driverClassName: org.postgresql.Driver
  datasource:
    url: jdbc:postgresql://localhost:5432/chat
    username: postgres
    password: admin

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  liquibase:
    change-log: classpath:/config/liquibase/master.xml
    enabled: true

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp


org:
  springframework:
    security:
      level: DEBUG